=== billgoo/WHU-ISS-XML/实验一/SpyBase2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<!ENTITY % pc "(#PCDATA)">
<!ENTITY % c "CDATA">
<!ELEMENT info (spyTable)>
<!ELEMENT spyTable (row)+>
<!ELEMENT row (firstName, lastName, (missionList)*, (aliasList)*)>
<!ELEMENT aliasList (alias)>
<!ELEMENT missionList (date, description, status)>
<!ELEMENT firstName %pc;>
<!ELEMENT lastName %pc;>
<!ELEMENT alias %pc;>
<!ELEMENT date %pc;>
<!ELEMENT description %pc;>
<!ELEMENT status %pc;>
<!ATTLIST row
	spyID %c; #REQUIRED
>
<!ATTLIST aliasList
	aID %c; #REQUIRED
>
<!ATTLIST missionList
	mID %c; #REQUIRED
>

=== billgoo/WHU-ISS-XML/实验一/SpyBase2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<!DOCTYPE info SYSTEM "SpyBase2.dtd">
<info>
	<spyTable>
		<row spyID="A001">
			<firstName>Nikki</firstName>
			<lastName>Devgood</lastName>
			
			<missionList mID="M101">
				<date>2005-4-15</date>
				<description>Crack the code</description>
				<status>Mission Accomplished</status>
			</missionList>
			<missionList mID="M102">
				<date>2006-2-15</date>
				<description>Get the source</description>
				<status>Mission Accomplished</status>
			</missionList>
			<missionList mID="M103">
				<date>2006-5-4</date>
				<description>Hit the target</description>
				<status>In Progress</status>
			</missionList>
			<aliasList aID="1">
				<alias>Spy Grrrl</alias>
			</aliasList>
			<aliasList aID="2">
				<alias>La Femme Nikki</alias>
			</aliasList>
		</row>
		<row spyID="A006">
			<firstName>Link</firstName>
			<lastName>Lister</lastName>
			<missionList mID="M104">
				<date>2006-6-15</date>
				<description>Shoot the rapid</description>
				<status>In Progress</status>
			</missionList>
			<aliasList aID="3">
				<alias>LL</alias>
			</aliasList>
			<aliasList aID="4">
				<alias>Fred</alias>
			</aliasList>
		</row>
		<row spyID="A003">
			<firstName>Danger</firstName>
			<lastName>Mause</lastName>
			<missionList mID="M105">
				<date>2005-11-4</date>
				<description>Get the &lt;big cheese&gt;</description>
				<status>In Progress</status>
			</missionList>
			<missionList mID="M106">
				<date>2006-4-4</date>
				<description>Map the area</description>
				<status>In Progress</status>
			</missionList>
			<aliasList aID="5">
				<alias>Big Ears</alias>
			</aliasList>
		</row>
		<row spyID="A099">
			<firstName>Barbara</firstName>
			<lastName>Feldon</lastName>
			<missionList mID="M107">
				<date>2006-5-2</date>
				<description>Get Smart</description>
				<status>In Progress</status>
			</missionList>
		</row>
		<row spyID="A004">
			<firstName>Maxwell</firstName>
			<lastName>Smart</lastName>
			<missionList mID="M108">
				<date>1967-2-15</date>
				<description>Protect Chief</description>
				<status>In Progress</status>
			</missionList>
			<missionList mID="M109">
				<date>2006-6-15</date>
				<description>Get some style</description>
				<status>Mission Accomplished</status>
			</missionList>
			<aliasList aID="6">
				<alias>Inspector Gadget</alias>
			</aliasList>
			<aliasList aID="7">
				<alias>Don Adams</alias>
			</aliasList>
			
		</row>
	</spyTable>
</info>
