=== billgoo/WHU-ISS-XML/实验二/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>Comment describing your root element</xs:documentation>
	</xs:annotation>
	<xs:element name="Book">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="titleType"/>
				<xs:element name="author" type="xs:string" maxOccurs="3"/>
				<xs:element name="section" type="sectionType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="titleType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="bookTitleType">
		<xs:restriction base="titleType">
			<xs:enumeration value="Data On The Web"/>
			<xs:enumeration value="TCP/IP Illustrated"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sectionTitleType">
		<xs:restriction base="titleType">
			<xs:pattern value="1(\-1)?\..+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="figureTitleType">
		<xs:restriction base="titleType">
			<xs:pattern value="1\-1(\-1)?\..+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="sectionType">
		<xs:sequence>
			<xs:element name="title" type="titleType"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="p"/>
				<xs:element name="figure">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="titleType"/>
							<xs:element name="image">
								<xs:complexType>
									<xs:attribute name="source" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="width" use="required"/>
						<xs:attribute name="height" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="section" type="sectionType"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id"/>
		<xs:attribute name="difficulty"/>
	</xs:complexType>
</xs:schema>

=== billgoo/WHU-ISS-XML/实验二/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<Book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="book.xsd">
	<title xsi:type="titleType">TCP/IP Illustrated</title>
	<author>XCJ</author>
	<section>
		<title xsi:type="titleType">1.1</title>
		<figure width="" height="">
			<title xsi:type="titleType">1-1.1</title>
			<image source=""/>
		</figure>
	</section>
</Book>
