=== billgoo/WHU-ISS-XML/实验二/SpyBase1_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--被XMLSpy vW3C Schema产生的2013 sp1 () (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sb="http://www.xml.org.cn/namespaces/SpyBase" targetNamespace="http://www.xml.org.cn/namespaces/SpyBase" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="status">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="In progress"/>
				<xs:enumeration value="Mission Accomplished"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="spyTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sb:row" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="spyID_key">
			<xs:selector xpath=".//spyID"/>
			<xs:field xpath="."/>
		</xs:key>
	</xs:element>
	<xs:element name="spyREF">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="row">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="sb:spyREF"/>
					<xs:choice>
						<xs:element ref="sb:alias"/>
						<xs:sequence>
							<xs:element ref="sb:date"/>
							<xs:element ref="sb:description"/>
							<xs:element ref="sb:status"/>
						</xs:sequence>
					</xs:choice>
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="sb:firstName"/>
					<xs:element ref="sb:lastName"/>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="spyID">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="A001"/>
						<xs:enumeration value="A003"/>
						<xs:enumeration value="A004"/>
						<xs:enumeration value="A006"/>
						<xs:enumeration value="A099"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="mID">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="M101"/>
						<xs:enumeration value="M102"/>
						<xs:enumeration value="M103"/>
						<xs:enumeration value="M104"/>
						<xs:enumeration value="M105"/>
						<xs:enumeration value="M106"/>
						<xs:enumeration value="M107"/>
						<xs:enumeration value="M108"/>
						<xs:enumeration value="M109"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="aID">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="4"/>
						<xs:enumeration value="5"/>
						<xs:enumeration value="6"/>
						<xs:enumeration value="7"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="missionTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sb:row" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="mID_key">
			<xs:selector xpath=".//mID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:keyref name="spyREF_keyref_2" refer="sb:spyID_key">
			<xs:selector xpath="./spyTable/spyID"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="lastName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Devgood"/>
				<xs:enumeration value="Feldon"/>
				<xs:enumeration value="Lister"/>
				<xs:enumeration value="Mause"/>
				<xs:enumeration value="Smart"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="firstName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Barbara"/>
				<xs:enumeration value="Danger"/>
				<xs:enumeration value="Link"/>
				<xs:enumeration value="Maxwell"/>
				<xs:enumeration value="Nikki"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="description">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Crack the code"/>
				<xs:enumeration value="Get smart"/>
				<xs:enumeration value="Get some style"/>
				<xs:enumeration value="Get the big cheese"/>
				<xs:enumeration value="Get the source"/>
				<xs:enumeration value="Hit the target"/>
				<xs:enumeration value="Map the area"/>
				<xs:enumeration value="Protect Chief"/>
				<xs:enumeration value="Shoot the rapid"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="date">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{4}\-([1-9]|(1[0-2]))\-\d{1,2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="aliasTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sb:row" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="aID_key">
			<xs:selector xpath=".//aID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:keyref name="spyREF_keyref_1" refer="sb:spyID_key">
			<xs:selector xpath="./spyTable/spyID"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="alias">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Big Ears"/>
				<xs:enumeration value="Don Adams"/>
				<xs:enumeration value="Fred"/>
				<xs:enumeration value="Inspector Gadget"/>
				<xs:enumeration value="LL"/>
				<xs:enumeration value="La Femme Nikki"/>
				<xs:enumeration value="Spy Grrrl"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SpyBase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sb:aliasTable"/>
				<xs:element ref="sb:missionTable"/>
				<xs:element ref="sb:spyTable"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== billgoo/WHU-ISS-XML/实验二/SpyBase1_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<SpyBase xmlns="http://www.xml.org.cn/namespaces/SpyBase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xml.org.cn/namespaces/SpyBase SpyBase1_2.xsd">
	<aliasTable>
		<row aID="1">
			<spyREF>A001</spyREF>
			<alias>Spy Grrrl</alias>
		</row>
		<row aID="2">
			<spyREF>A001</spyREF>
			<alias>La Femme Nikki</alias>
		</row>
		<row aID="3">
			<spyREF>A006</spyREF>
			<alias>LL</alias>
		</row>
		<row aID="4">
			<spyREF>A006</spyREF>
			<alias>Fred</alias>
		</row>
		<row aID="5">
			<spyREF>A003</spyREF>
			<alias>Big Ears</alias>
		</row>
		<row aID="6">
			<spyREF>A004</spyREF>
			<alias>Inspector Gadget</alias>
		</row>
		<row aID="7">
			<spyREF>A004</spyREF>
			<alias>Don Adams</alias>
		</row>
	</aliasTable>
	<missionTable>
		<row mID="M101">
			<spyREF>A001</spyREF>
			<date>2005-4-15</date>
			<description>Crack the code</description>
			<status>Mission Accomplished</status>
		</row>
		<row mID="M102">
			<spyREF>A001</spyREF>
			<date>2006-2-15</date>
			<description>Get the source</description>
			<status>Mission Accomplished</status>
		</row>
		<row mID="M103">
			<spyREF>A001</spyREF>
			<date>2006-5-4</date>
			<description>Hit the target</description>
			<status>In progress</status>
		</row>
		<row mID="M104">
			<spyREF>A006</spyREF>
			<date>2006-6-15</date>
			<description>Shoot the rapid</description>
			<status>In progress</status>
		</row>
		<row mID="M105">
			<spyREF>A003</spyREF>
			<date>2005-11-4</date>
			<description>Get the big cheese</description>
			<status>In progress</status>
		</row>
		<row mID="M106">
			<spyREF>A003</spyREF>
			<date>2006-4-4</date>
			<description>Map the area</description>
			<status>In progress</status>
		</row>
		<row mID="M107">
			<spyREF>A099</spyREF>
			<date>2006-5-2</date>
			<description>Get smart</description>
			<status>In progress</status>
		</row>
		<row mID="M108">
			<spyREF>A004</spyREF>
			<date>1967-2-15</date>
			<description>Protect Chief</description>
			<status>In progress</status>
		</row>
		<row mID="M109">
			<spyREF>A004</spyREF>
			<date>2006-6-15</date>
			<description>Get some style</description>
			<status>Mission Accomplished</status>
		</row>
	</missionTable>
	<spyTable>
		<row spyID="A001">
			<firstName>Nikki</firstName>
			<lastName>Devgood</lastName>
		</row>
		<row spyID="A006">
			<firstName>Link</firstName>
			<lastName>Lister</lastName>
		</row>
		<row spyID="A003">
			<firstName>Danger</firstName>
			<lastName>Mause</lastName>
		</row>
		<row spyID="A099">
			<firstName>Barbara</firstName>
			<lastName>Feldon</lastName>
		</row>
		<row spyID="A004">
			<firstName>Maxwell</firstName>
			<lastName>Smart</lastName>
		</row>
	</spyTable>
</SpyBase>
